version: "3.5"

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
      MYSQL_USER: gyl
      MYSQL_PASSWORD: 'gyl'
      MYSQL_DATABASE: gyl
    volumes:
      - ./db:/var/lib/mysql
  gyl:
    image: green-your-look
    restart: always
    ports: 
      - "8542:8542"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: gyl
      DB_USER: gyl
      DB_PASS: 'gyl'
    depends_on:
      - db
