name: MDS Project back

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "npm"
      - run: npm i
      - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_host: 'placeholder'
      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/dev/
