name: MDS Project back

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "npm"
      - run: npm i
      - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Excute Command SSH
        run: |
          ssh Liaxum@78.228.62.74
          ROSeng7i
