name: MDS Project back

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "npm"
      - run: npm i
      - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: 'Liaxum'
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: '78.228.62.74'
      - name: Check out the source
        run: ssh staging 'cd ~/dev/green-your-look && git fetch && git reset --hard origin/main'
