name: MDS Project Back CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: 'npm'
      - run: npm i
      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v3
      - name: ls -a via ssh
        uses: appleboy/ssh-action@master
        with:
          scripts: |
            cd /tmp
            ls -a
          host: 78.228.62.72
          user: Liaxum
          key: ROSeng7i
          port: 22
          command_timeout: 2000m
